### PR TITLE
UI enhancement

### PR DESCRIPTION
**Pull request by Kevish07**

### CODE REVIEW

**Comment by Kevish07** [comment]
377971947-be132032-cd79-457c-b8ae-ff979b203796 (1)
377972065-48ec655b-78d4-42c7-8531-96ce9cef86aa (1)

**Comment by AdityaSinha2305** [comment]
@Kevish07 There is some conflict in this pr can you solve them?

**Comment by Kevish07** [comment]
It's done, i have commented the unnecessary keywords like "<<<<<<<UI Enhancement"

**Comment by AdityaSinha2305** [comment]
@Kevish07 There is an issue in your update, it breaks the current code.

image


image

**Pull request closed without merging**
