### PR TITLE
"undefined" issue fixed

### LINKED ISSUE #26: Fixing the logic
Fixing the logic of the code to avoid getting "undefined" in the captcha and making the program more efficient when regenerating the captcha.

Assign it to me.

Screenshot 2024-10-13 at 12 28 22 PM

### PR DESCRIPTION
**Pull request by kshitijakarsh**
fixes #26 

Looping avoids generating "undefined" and fixes the index at which "undefined" is present rather than regenerating the whole captcha.

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@kshitijakarsh You have removed the start button in this pr.

image

**Comment by AdityaSinha2305** [comment]
@kshitijakarsh Avoid creating pr through main branch.
Create a new branch for your feature and then create pr.
You can go through the guidelines once.

**Comment by kshitijakarsh** [comment]
Hey fixed the issue, review the code again and do tell me if there are more corrections to be made. I'll look into the guidelines and work with multiple branches, thank you for the advice.

**Comment by AdityaSinha2305** [comment]
@kshitijakarsh There is some conflicts do resolve them and I'll merge this if the changes made by you works fine.

**Pull request closed without merging**
