### PR TITLE
distinct font and color for code which makes any AI to process more

### PR DESCRIPTION
**Pull request by v-aibha-v-jain**

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@v-aibha-v-jain Can you share the screenshot of your work, what changes you have made?

**Comment by v-aibha-v-jain** [comment]
ya sure since I'm in clg right now so I can share a phone screen recording

**Comment by AdityaSinha2305** [comment]
@v-aibha-v-jain Your work is great but can you make styling little bit simple so that captcha can easily understandable.

Like in this it's confusing to know whether 2nd letter is 'l' or 'e'

image

**Comment by AdityaSinha2305** [comment]
@v-aibha-v-jain Once done with the required changes, I will be happy to merge this pull request.
Keep contributing and if you like this repo don't forget to star it will help other contributors as well.
Thanks!!

**Comment by v-aibha-v-jain** [comment]
ya sure I don't have my laptop right now
so I will surely do it this evening
and also look for the fonts

**Pull request closed without merging**
