### PR TITLE
Fixed Redirect UI

### PR DESCRIPTION
**Pull request by VinayGadKerkar**
Resolves https://github.com/AdityaSinha2305/ForkTheCaptcha/issues/93
-Matches the UI of the alert
-Makes it prettier

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@VinayGadKerkar Can you share your work screenshot?

**Comment by VinayGadKerkar** [comment]
Screenshot 2024-10-25 001048

**Comment by AdityaSinha2305** [comment]
@VinayGadKerkar I am unable to see the changes you have made in UI of alert. Can you share that picture of UI?

**Comment by VinayGadKerkar** [comment]
Uploading Untitled video - Made with Clipchamp.mp4…

**Comment by VinayGadKerkar** [comment]
before

**Comment by VinayGadKerkar** [comment]
Uploading Untitled video - Made with Clipchamp (1).mp4…

**Comment by VinayGadKerkar** [comment]
after

**Comment by VinayGadKerkar** [comment]
https://github.com/user-attachments/assets/12d2af10-a70d-46d7-a21b-22ea1b189edf

**Comment by VinayGadKerkar** [comment]
after

**Comment by VinayGadKerkar** [comment]
https://github.com/user-attachments/assets/f09b69ce-77e4-42b1-bbd6-f06152d75d36

**Comment by AdityaSinha2305** [comment]
@VinayGadKerkar There are some recent changes in the UI of the login page. Please update your fork with the main.

**Comment by VinayGadKerkar** [comment]
> @VinayGadKerkar There are some recent changes in the UI of the login page. Please update your fork with the main.
done

**Comment by AdityaSinha2305** [comment]
@VinayGadKerkar Nice fix!! keep contributing.

**Pull request merged**
