### PR TITLE
added more security

### PR DESCRIPTION
**Pull request by Vai-Man**
I implemented the feature mentioned in #76

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@Vai-Man Your work is great but it breaks the background of the captcha.
Also could you resolve the conflict and implement this feature on math captcha as well?

**Comment by Vai-Man** [comment]
> @Vai-Man Your work is great but it breaks the background of the captcha.

Yes, I did notice that. For the time being, I thought the captcha was rendering an image, so why render a background. We can do that later.

> Also could you resolve the conflict and implement this feature on math captcha as well?

Could you create an issue and raise it, as it will be a separate implementation.
I would love to work on it separately and incorporate other ideas as well.

**Comment by Vai-Man** [comment]
Just fixed the conflicts :)

**Comment by AdityaSinha2305** [comment]
@Vai-Man Background is for better UI. Sure I will create a new issue for that.

**Comment by Vai-Man** [comment]
> @Vai-Man Background is for better UI.

 Yup I have incorporated the background :)

**Comment by AdityaSinha2305** [comment]
@Vai-Man Kudos!! great work. Keep contributing.

**Comment by AdityaSinha2305** [comment]
@Vai-Man This feature breaks the live code.

**Pull request merged**
