### PR TITLE
Refactor : Start button style with overall CSS

### PR DESCRIPTION
**Pull request by 2021eo3ar**
I have modified the overall styling, So that the whole webstie can appear 
in much better way to every screen size

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@2021eo3ar Can you share your work screenshot and also this PR has some conflicts do resolve them.
Don't forget to sync your fork.

**Comment by 2021eo3ar** [comment]
yes here is the screen shot of my work - 
Screenshot 2024-10-13 193113

**Comment by 2021eo3ar** [comment]
And for the Confilicts I want you to accept my changes those are made to make website more appealing and professional.

**Comment by 2021eo3ar** [comment]
Hey @AdityaSinha2305 I have resolved the merge conflicts kindly merge my branch with hactoberfest label.

**Comment by AdityaSinha2305** [comment]
@2021eo3ar There is some issue with your work for the long captcha content.


image

**Pull request closed without merging**
