### PR TITLE
Added Styles to the alert

### PR DESCRIPTION
**Pull request by VinayGadKerkar**
Made the alert fancy and in more prettier using external library

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@VinayGadKerkar There is some conflict in this do resolve them.

**Comment by VinayGadKerkar** [comment]
Done

**Comment by AdityaSinha2305** [comment]
@VinayGadKerkar When entering invalid captcha double alert is coming.
One original dialog box and one styled alert created by you.
Can you fix this?

**Comment by VinayGadKerkar** [comment]
> @VinayGadKerkar When entering invalid captcha double alert is coming. One original dialog box and one styled alert created by you. Can you fix this?

already fixed in above commit

**Comment by AdityaSinha2305** [comment]
Kudos!! great work.
Keep contributing.

**Pull request merged**
