### PR TITLE
Visitors Count Added #65

### PR DESCRIPTION
**Pull request by yamini1183**
Issue #65 

Added visitors count feature and gave it styling.

### CODE REVIEW

**Comment by yamini1183** [comment]
https://github.com/user-attachments/assets/bbfbf51c-13e0-4ade-95bb-7df5c495fc4a

Here is the demo

**Comment by AdityaSinha2305** [comment]
@yamini1183 Your work is great but it breaks the captcha and footer alignment. Can you resolve this and I'll happy to merge this feature.

image

**Comment by yamini1183** [comment]
Hey @AdityaSinha2305 Please review the changes.

**Comment by AdityaSinha2305** [comment]
@yamini1183 Kudos!! great work. Thanks for implementing a new feature.
Keep contributing and looking forward for more such new features.

**Comment by AdityaSinha2305** [comment]
Hey @yamini1183 this 'total visits' just works for an individual machine and not publicly. Can you implement for public user so that actual total visit count is visible for the website? 

You can check by clicking on this link that each time it starts from 0.

https://adityasinha2305.github.io/ForkTheCaptcha/

**Comment by yamini1183** [comment]
Sure I will try to get it done by tomorrow.

**Pull request merged**
