### PR TITLE
added login page redirect after submitting captcha

### PR DESCRIPTION
**Pull request by Nitinkumar-29**
Ok, after submitting correct captcha, use will be redirect to the login page as they press "ok" button on confirm prompt.

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@Nitinkumar-29 Can you share the screenshot of your work and there is some conflict in this PR do resolve them also.
Don't forget to sync your fork.

**Comment by Nitinkumar-29** [comment]
Yes, I'll provide login page screenshot, just resolved all the conflicts in work tree.
Screenshot 2024-10-13 221401

**Comment by AdityaSinha2305** [comment]
@Nitinkumar-29 Your work is great but there is small issue, even if I click on 'cancel' after valid captcha it is redirecting to login page which is an issue.
Can you resolve this issue?

**Comment by AdityaSinha2305** [comment]
@Nitinkumar-29 Are you still working on this pr or should I close this one?

**Comment by Nitinkumar-29** [comment]
I did made the changes as you can see in a522767.... commit. 

You definitely can merge changes and close this issue. And thanks for allowing me to work on this one.

**Comment by AdityaSinha2305** [comment]
@Nitinkumar-29 Kudos!! great work.

**Pull request merged**
