### PR TITLE
Nav bar final

### PR DESCRIPTION
**Pull request by mahirabidi12**
I have made the required changes please merge it under hacktoberfest label

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@mahirabidi12 Is there any issue with this PR?

**Comment by mahirabidi12** [comment]
I was working upon making the nav bar responsive as well . I have completed the html and css.

**Comment by mahirabidi12** [comment]
Please open the pull request and add the hacktoberfest tag so that i can upload it .

**Comment by AdityaSinha2305** [comment]
@mahirabidi12 I have reopened the pull request, you can now do the necessary changes.

**Comment by mahirabidi12** [comment]
Please add the hacktoberfest label as well

**Pull request closed without merging**
