### PR TITLE
creating challenging captcha with diff fonts

### PR DESCRIPTION
**Pull request by v-aibha-v-jain**

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@v-aibha-v-jain There is some conflict occur in this, do resolve them.

**Comment by v-aibha-v-jain** [comment]
done can u try to merge now

**Comment by AdityaSinha2305** [comment]
@v-aibha-v-jain Sorry for the delay, but there is lots of conflicts in this pr as the main branch updated.

**Comment by v-aibha-v-jain** [comment]
ok, will open a new one

**Pull request closed without merging**
