### PR TITLE
Add footer to home page

### PR DESCRIPTION
**Pull request by anushree0809**
I have added the same footer to Home Page as its in the About page. 
image

This is how it looks.

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@anushree0809 Your work looks fine but make sure there is some gap between body content and footer.
Can you fix it?

image

**Comment by anushree0809** [comment]
Ok, will update the PR after fixing.

**Comment by anushree0809** [comment]
Does this look better?
image

**Comment by AdityaSinha2305** [comment]
Yeah it looks better now.
Kudos!! nice work
Keep contributing.

**Pull request merged**
